server:
  port: '8999'

spring:
  application:
    name: ms1

  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mission?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000

    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 929203548061-no061dftv652em16a1049jnhfu966qn2.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile

          kakao:
            client-id: b221dd8bfb98b9c63a6c1cfe7fdd41f0
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8999/login/oauth2/code/kakao

          naver:
            client-id: _IhF42SeXiUu06U3VVzb
            client-secret: kYnCF89JRG
            redirect-uri: http://localhost:8999/login/oauth2/code/naver
            authorization-grant-type: authorization_code

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response